### ISSUE TITLE
Upgrade to node 12 has breaking change with JSON.stringify

### ISSUE THREAD

**Issue by gsouf** [apify/apify-actor-docker#16] opened 2020-02-22 11:25 UTC
Node 12 introduced a breaking change with JSON.stringify. https://github.com/tc39/ecma262/issues/944

The result is that the JSON produced by JSON.stringify might be different from what it was with NODE 10 and is not compatible with some json decoders from other languages. That's the case with the funciton json_decode from PHP.

Without a direct obvious fix we are going to fork this one stick to node 10, that I encourage you to do too.

**Comment by metalwarrior665** [comment] 2020-02-22 13:02
Specifically, the issue is caused by this:
https://stackoverflow.com/questions/58674104/php-json-decode-does-not-work-with-single-unpaired-surrogate-caused-by-node-12-w

**Comment by gsouf** [comment] 2020-02-24 14:12
https://hub.docker.com/r/apify/actor-node-chrome

A few issues here

- Still saying "node 10" in the desc
- no tag available to keep using node 10

Keep in mind that bumping to a major version of a vendor without any warning nor fallback can have lot of consequences for users

**Comment by jancurn** [comment] 2020-02-24 14:52
@gsouf Thanks for the report, we've fixed the descriptions.

You are right, we need to be more careful with upgrading major release. We'll consider introducing tags like `node-10` or `10` for Docker images that will let you keep an older version for some time.

**Comment by B4nan** [comment] 2021-11-12 08:13
Closing as this seems very outdated, and we now release imagines with tags so you can stay on given node version (but we now support node 15/16 only anyway 🤷)

**Closed by B4nan** 2021-11-12 08:13 UTC
